version: '3'
services:
  postgres:
    image: postgres:9.6.1
    ports:
      - 5432:5432

  app:
    restart: always
    build: ./docker/app
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./app:/app/
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
